name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  load-starboard:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.8.1
    - name: Setup Starboard cache
      uses: actions/cache@v2
      with:
        path: ./starboard-dist
        key: starboard
    - run: ./scripts/starboard.ts latest
  client-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: Setup Node dependency cache
      uses: actions/cache@v2
      with:
        # Cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Archive client build
      uses: actions/upload-artifact@v2
      with:
        name: client-build
        # Even though this has "working-directory: client" it needs a full path...
        path: |
          client/build
          !client/build/**/*.map
  server-build:
    runs-on: ${{ matrix.os }}
    needs: client-build
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@v2
      with:
        deno-version: v1.8.1

    - name: Download client
      uses: actions/download-artifact@v2
      with:
        name: client-build
        path: client/build

    - name: Setup Starboard cache
      uses: actions/cache@v2
      with:
        path: ./starboard-dist
        key: starboard

    - name: Test?
      run: deno test deno/lib/byte_size.ts

    - name: Compile all
      run: |
        ./scripts/compile.ts --lite --output=bin/localstar-[target] \
          --allow-read --allow-net ./deno/localstar_server.ts

    - name: Embed all
      run: |
        ./scripts/embed.ts --root=./client/build --root=./starboard-dist \
          bin/localstar-*

    - name: Archive Apple ARM 64
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: localstar-aarch64-apple-darwin
        path: bin/localstar-aarch64-apple-darwin

    - name: Archive Apple x86-64
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: localstar-x86_64-apple-darwin
        path: bin/localstar-x86_64-apple-darwin

    - name: Archive Windows
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: localstar-x86_64-pc-windows-msvc
        path: bin/localstar-x86_64-pc-windows-msvc

    - name: Archive Linux
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: localstar-x86_64-unknown-linux-gnu
        path: bin/localstar-x86_64-unknown-linux-gnu
